#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

groups:
  - docker
  
users:
  - default
  # the docker service account
  - name: docker-service
    groups: docker

system_info:
  default_user:
    groups: [docker]
    name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL


final_message: "The system is finally up, after $UPTIME seconds"

runcmd:
  - sudo usermod -aG docker $USER
  - sudo systemctl enable docker.service
  - sudo systemctl start docker.service
  - sudo id $USER
  #- sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  #- sudo chmod +x /usr/local/bin/docker-compose
  - sudo hostnamectl set-hostname BACKEND-TEASTORE 
  #- cd /tmp && git clone https://github.com/jpianigiani-cisco/aws-mcd-app.git 
#  - sudo docker-compose -f /webapp-aws-mcd/modules/app-infra-aws/scripts/docker-compose_default_backend.yaml up -d 
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -y update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io
  - sudo systemctl enable docker
  - sudo id $USER

  # install docker-compose following the guide: https://docs.docker.com/compose/install/
  #- sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  #- sudo chmod +x /usr/local/bin/docker-compose

power_state:
  mode: reboot
  message: Restarting after installing docker & docker-compose

