#cloud-config

system_info:
  default_user:
    name: ec2-user
    sudo: ALL=(ALL) NOPASSWD:ALL

package_update: true
package_upgrade: true

packages:
  - git
  - docker.io
  - unattended-upgrades

groups:
  - docker

users:
 - name: ubuntu
 - groups: docker

runcmd:
  - sudo newgrp docker
  - sudo usermod -a -G docker ec2-user
  - sudo systemctl enable docker.service
  - sudo systemctl start docker.service
  - sudo id ec2-user
  #- sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  #- sudo chmod +x /usr/local/bin/docker-compose
  - sudo hostnamectl set-hostname BACKEND-TEASTORE 
  #- cd /tmp && git clone https://github.com/jpianigiani-cisco/aws-mcd-app.git 
#  - sudo docker-compose -f /webapp-aws-mcd/modules/app-infra-aws/scripts/docker-compose_default_backend.yaml up -d 

system_info:
  default_user:
    groups: [docker]

final_message: "The system is finally up, after $UPTIME seconds"
