#cloud-config

package_update: true
package_upgrade: true

packages:
  - git
  - docker.io
  - unattended-upgrades

groups:
  - docker

users:
 - name: ubuntu
 - groups: docker

system_info:
  default_user:
    groups: [docker]
    name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL

final_message: "The system is finally up, after $UPTIME seconds"

runcmd:

# TEMP
  - curl -fsSL https://get.docker.com | sh
#TEMP
  - sudo usermod -aG docker $USER
  - sudo systemctl enable docker.service
  - sudo systemctl start docker.service
  - sudo id $USER
  #- sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  #- sudo chmod +x /usr/local/bin/docker-compose
  - sudo hostnamectl set-hostname FRONTEND-TEASTORE 
  #- cd /tmp && git clone https://github.com/jpianigiani-cisco/aws-mcd-app.git
#  - sudo docker-compose -f /webapp-aws-mcd/modules/app-infra-aws/scripts/docker-compose_default_frontend.yaml up -d



