#cloud-config

package_update: true
package_upgrade: true

packages:
  - git
  - docker.io
  - unattended-upgrades

groups:
  - docker

users:
 - name: ubuntu
 - groups: docker, admin, sudo

system_info:
  default_user:
    groups: [docker]
    name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL

final_message: "The system is finally up, after $UPTIME seconds"



runcmd:
  - sudo hostnamectl set-hostname FRONTEND-TEASTORE 
  - sudo usermod -aG sudo $USER
  - sudo usermod -aG docker $USER
  - sudo id $USER
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -y update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io
  - sudo systemctl enable docker
  - sudo systemctl start docker.service
  - sudo id $USER
  - touch /tmp/signal
  #- cd /tmp && git clone https://github.com/jpianigiani-cisco/aws-mcd-app.git
#  - sudo docker-compose -f /webapp-aws-mcd/modules/app-infra-aws/scripts/docker-compose_default_frontend.yaml up -d


